
name: Nodejs

on:
  push:
    branches:
    - main
    - ci/**
  pull_request:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - id: start
      name: dc start
      uses: jehon/actions-devcontainer@main
      with:
        action: start

    - name: npm ci
      uses: jehon/actions-devcontainer@main
      with:
        run: npm ci

    - name: npm test
      uses: jehon/actions-devcontainer@main
      with:
        run: JH_TMDB_KEY=${{ secrets.JH_TMDB_KEY }} npm test

    - name: npm lint
      uses: jehon/actions-devcontainer@main
      with:
        run: npm run lint

    - name: dc stop
      uses: jehon/actions-devcontainer@main
      if: always()
      with:
        action: stop