
on:
  push:
    branches:
    - main
    - ci/**
  pull_request:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    
    - id: Configure
      run: mkdir --mode=0777 -p $HOME/restricted && echo "${{ secrets.JH_TMDB_KEY }}" > $HOME/restricted/tmdb.key

    - name: npm ci
      uses: devcontainers/ci@v0.3
      with:
        runCmd: npm ci

    - name: npm test
      uses: devcontainers/ci@v0.3
      with:
        runCmd: npm test

    - name: npm lint
      uses: devcontainers/ci@v0.3
      with:
        runCmd: npm run lint
