
on:
  push:
    branches:
    - main
    - ci/**
  pull_request:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f

    - uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: setup
      run: sudo .devcontainer/setup.sh

    - name: Configure key
      run: mkdir --mode=0777 -p $HOME/restricted && echo "${{ secrets.JH_TMDB_KEY }}" > $HOME/restricted/tmdb.key

    - run: npm ci

    - run: npm test

    - run: npm run lint
